spring.application.name=Healthcare

spring.datasource.url=jdbc:mysql://localhost:3306/careassist?useSSL=false&allowPublicKeyRetrieval=true&serverTimezone=UTC
spring.datasource.username=root
spring.datasource.password=Manojkanna2005
spring.datasource.driver-class-name=com.mysql.cj.jdbc.Driver


spring.jpa.hibernate.ddl-auto=update
spring.jpa.show-sql=true
spring.jpa.properties.hibernate.format_sql=true

jwt.secret=CareAssistJwtSecretKeyForHexawareProject1234567890
jwt.expiration=3600000

springdoc.swagger-ui.path=/swagger-ui.html

spring.security.oauth2.client.registration.github.client-id=Ov23liU6ID2U5EzPUkKx
spring.security.oauth2.client.registration.github.client-secret=46ba384103128783bed423f79acea0ff7c4c112c
spring.security.oauth2.client.registration.github.scope=read:user,user:email


app.frontend-url=http://localhost:5173/
spring.servlet.multipart.enabled=true
spring.servlet.multipart.max-file-size=5MB
spring.servlet.multipart.max-request-size=30MB
app.claim-documents.storage-dir=${CLAIM_DOCUMENT_STORAGE_DIR:uploads/claim-documents}

app.mail.enabled=true
app.mail.from=emailsender2005manoj@gmail.com
spring.mail.host=smtp.gmail.com
spring.mail.port=587
spring.mail.username=emailsender2005manoj@gmail.com
spring.mail.password=ialr zklq fyyw pmrx
spring.mail.properties.mail.smtp.auth=true
spring.mail.properties.mail.smtp.starttls.enable=true
spring.mail.properties.mail.smtp.starttls.required=true

app.cors.allowed-origins=http://localhost:5173,http://frontend-impl-bucket.s3-website-us-east-1.amazonaws.com

server.port=8080
server.address=0.0.0.0
